spring.application.name=spring-web
##Datasource de MariaDb
spring.jpa.hibernate;ddl-auto=auto
spring.jpa.show-sql=true

spring.datasource.url=jdbc:mariadb://localhost:3306/springweb?useSSL=false&serverTimezone=UTC
spring.datasource.username=springwebowner
spring.datasource.password=1
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

###server.port=8082

##Cambiar las rutas de thymeleaf
spring.thymeleaf.prefix=classpath:/paginas/
spring.thymeleaf.suffix=.html

##mensaje para enviarselo a la vista

mensaje.application=Aplicaci\u00F3n Web con Spring MVC



##
spring.jpa.hibernate.ddl-auto=create
##spring.jpa.show-sql=true
spring.datasource.hikari.connection-timeout=20000
spring.datasource.hikari.maximum-pool-size=5
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
# Ejecutar data.sql despu\u00E9s de crear las tablas
spring.jpa.defer-datasource-initialization=false
#always,never
spring.sql.init.mode=never